styles.style = {
    icons = {
        logo = {
            vim = "",
            toml = "",
            go = "",
            rust = "",
            lua = "",
            python = "",
            sh = "",
            js = "",
            ts = "",
            html = "",
            css = "",
            json = "",
            java = "",
            tar = "󰛫",
        },
        documents = {
            file = "",
            restart = "",
            harpoon_files = "",
            folder = "",
            folder_open = "",
            empty_folder = "",
            emtpy_folder_open = "",
            find = "",
        },
        misc = {
            close = "",
            telescope = "",
            lsp = "",
            terminal = "",
        },
        diagnostics = {
            error = "",
            warn = "",
            info = "",
            hint = "",
            debug = "",
            trace = "",
        },
        dap = {
            breakpoint = "",
            stopped = "󰔶",
        },
        separators = {
            half_circle_left = "",
            half_circle_right = "",
        },
    },
    banner = {
        [[  ███▄    █ ▓█████  ▒█████   ██▒   █▓ ██▓ ███▄ ▄███▓ ]],
        [[  ██ ▀█   █ ▓█   ▀ ▒██▒  ██▒▓██░   █▒▓██▒▓██▒▀█▀ ██▒ ]],
        [[ ▓██  ▀█ ██▒▒███   ▒██░  ██▒ ▓██  █▒░▒██▒▓██    ▓██░ ]],
        [[ ▓██▒  ▐▌██▒▒▓█  ▄ ▒██   ██░  ▒██ █░░░██░▒██    ▒██  ]],
        [[ ▒██░   ▓██░░▒████▒░ ████▓▒░   ▒▀█░  ░██░▒██▒   ░██▒ ]],
        [[ ░ ▒░   ▒ ▒ ░░ ▒░ ░░ ▒░▒░▒░    ░ ▐░  ░▓  ░ ▒░   ░  ░ ]],
        [[ ░ ░░   ░ ▒░ ░ ░  ░  ░ ▒ ▒░    ░ ░░   ▒ ░░  ░      ░ ]],
        [[    ░   ░ ░    ░   ░ ░ ░ ▒       ░░   ▒ ░░      ░    ]],
        [[          ░    ░  ░    ░ ░        ░   ░         ░    ]],
        [[                                 ░                   ]],
    },
}
